import { Component } from '@angular/core';

@Component({
  selector: 'app-produtos',
  standalone: true,
  imports: [],
  templateUrl: './produtos.component.html',
  styleUrl: './produtos.component.css'
})
export class ProdutosComponent {
  products = [
    {
      name: 'Barraca de Camping',
      image: '../../../assets/barraca1.png',
      description: 'Flash 6 NTK de montagem rápida e 3000mm de coluna d´água',
      value: 'R$ 4.158,20',
      discount: 'R$ 4.033,45',
    },
    {
      name: 'Barraca de Camping',
      image: '../../../assets/barraca2.png',
      description: 'Explorer 4/6 NTK com 2500mm de coluna d´água',
      value: 'R$ 3.112,40',
      discount: 'R$ 3.019,03',
    },
    {
      name: 'Barraca de Camping',
      image: '../../../assets/barraca3.png',
      description: 'Colorado NTK 5/6 pessoas e coluna d´água de 2500mm',
      value: 'R$ 2.403,00',
      discount: 'R$ 2.330,91',
    },
    {
      name: 'Barraca de Camping',
      image: '../../../assets/barraca4.png',
      description: 'NTK Indy GT 3/4 pessoas Coluna d´água de 2500mm',
      value: 'R$ 1.859,70',
      discount: 'R$ 1.803,91',
    },
    {
      name: 'Barraca Patagônia',
      image: '../../../assets/barraca5.png',
      description: 'NTK 4 pessoas com avancê 3000mm',
      value: 'R$ 1.560,90',
      discount: 'R$ 1.514,07',
    },
    {
      name: 'Mochila Duffle',
      image: '../../../assets/mochila1.png',
      description: 'Bag NTK para Viagens 70 Litros',
      value: 'R$ 511,00',
      discount: 'R$ 495,67',
    },
    {
      name: 'Mochila Duffle',
      image: '../../../assets/mochila2.png',
      description: 'BK NTK para Viagens 20L',
      value: 'R$ 235,00',
      discount: 'R$ 227,95',
    },
    {
      name: 'Mochila Cargueira',
      image: '../../../assets/mochila3.png',
      description: 'Nautika Intruder 60 litros',
      value: 'R$ 589,50',
      discount: 'R$ 571,82',
    },
    {
      name: 'Mochila Semi-Cargueira',
      image: '../../../assets/mochila4.png',
      description: 'Nautika Intruder 45 litros',
      value: 'R$ 437,50',
      discount: 'R$ 424,38',
    },
    {
      name: 'Mochila Daypack',
      image: '../../../assets/mochila5.png',
      description: 'Street NTK',
      value: 'R$ 214,30',
      discount: 'R$ 207,87',
    },
    {
      name: 'Saco de dormir Kokan',
      image: '../../../assets/saco-dormir1.png',
      description: 'NTK solteiro para temperatura entre 6°C e 20°C',
      value: 'R$ 257,10',
      discount: 'R$ 249,39',
    },
    {
      name: 'Saco de dormir Bugy',
      image: '../../../assets/saco-dormir2.png',
      description: 'NTK solteiro para temperatura entre 8°C e 15°C',
      value: 'R$ 128,60',
      discount: 'R$ 124,74',
    },
    {
      name: 'Saco de dormir sarcófago Antartik',
      image: '../../../assets/saco-dormir3.png',
      description: 'NTK -7°C à 3°C',
      value: 'R$ 428,90',
      discount: 'R$ 416,03',
    },
    {
      name: 'Saco de dormir Everest do tipo sarcófago',
      image: '../../../assets/saco-dormir4.png',
      description: 'NTK -10°C a 5°C',
      value: 'R$ 522,00',
      discount: 'R$ 506,34',
    },
    {
      name: 'Saco de Dormir Viper',
      image: '../../../assets/saco-dormir5.png',
      description: 'Solteiro para Temperaturas entre 5°C à 12°C NTK',
      value: 'R$ 170,00',
      discount: 'R$ 164,90',
    },
    {
      name: 'Colchão inflável casal',
      image: '../../../assets/colchao1.png',
      description: 'Zenite com inflador incorporado que suporta 300kg NTK',
      value: 'R$ 493,10',
      discount: 'R$ 478,31',
    },
    {
      name: 'Colchão Inflável Solteiro Mirage',
      image: '../../../assets/colchao2.png',
      description: 'Nautika Até 100kg',
      value: 'R$ 191,70',
      discount: 'R$ 185,95',
    },
    {
      name: 'Colchão inflável casal Mirage',
      image: '../../../assets/colchao3.png',
      description: 'NTK que suporta até 200kg',
      value: 'R$ 299,50',
      discount: 'R$ 290,52',
    },
    {
      name: 'Colchão inflável king Brunei',
      image: '../../../assets/colchao4.png',
      description: 'Com altura extra dimensionada que suporta 250kg NTK',
      value: 'R$ 986,20',
      discount: 'R$ 956,61',
    },
    {
      name: 'Colchão inflável solteiro Zenite',
      image: '../../../assets/colchao5.png',
      description: 'Com inflador incorporado que suporta 100kg NTK',
      value: 'R$ 255,90',
      discount: 'R$ 248,22',
    },
    {
      name: 'Fogareiro de Mesa',
      image: '../../../assets/fogareiro1.png',
      description: 'Frontier com Maleta NTK',
      value: 'R$ 187,10',
      discount: 'R$ 181,49',
    },
    {
      name: 'Lampião Lanterna USB',
      image: '../../../assets/lampiao2.png',
      description: 'Radiant NTK 250 Lúmens Recarregável',
      value: 'R$ 170,00',
      discount: 'R$ 164,90',
    },
    {
      name: 'Fogareiro Stain',
      image: '../../../assets/fogareiro3.png',
      description: 'NTK em Aço Inox com Ignição Automática e Flex Fuel',
      value: 'R$ 227,80',
      discount: 'R$ 220,97',
    },
    {
      name: 'Fogareiro Átomo',
      image: '../../../assets/fogareiro4.png',
      description: 'NTK em Aço Inox com Sistema de Regulagem',
      value: 'R$ 101,40',
      discount: 'R$ 98,36',
    },
    {
      name: 'Lampião Cairo',
      image: '../../../assets/lampiao5.png',
      description: 'NTK com sistema de cartucho',
      value: 'R$ 227,80',
      discount: 'R$ 220,97',
    },
    {
      name: 'Cadeira dobrável Andrade',
      image: '../../../assets/cadeira1.png',
      description: 'De 1 estágio tamanho P NTK',
      value: 'R$ 170,50',
      discount: 'R$ 165,39',
    },
    {
      name: 'Banqueta Dobrável',
      image: '../../../assets/cadeira2.png',
      description: 'Para Camping Step 1 Verde NTK',
      value: 'R$ 65,00',
      discount: 'R$ 63,05',
    },
    {
      name: 'Cadeira Dobrável Nautika Boni',
      image: '../../../assets/cadeira3.png',
      description: 'Com Assento e Encosto Estofado',
      value: 'R$ 315,00',
      discount: 'R$ 305,55',
    },
    {
      name: 'Mesa dobrável Robust',
      image: '../../../assets/mesa4.png',
      description: 'Com ajuste de altura 80cm NTK',
      value: 'R$ 239,90',
      discount: 'R$ 232,70',
    },
    {
      name: 'Mesa dobrável Lua',
      image: '../../assets/mesa5.png',
      description: 'Com 4 porta copos da NTK',
      value: 'R$ 200,80',
      discount: 'R$ 194,78',
    }
  ];
}
